In [3]:

from card import Card
from deck import init_truco_deck
from actions import envido_actions, response_actions, truco_actions
import numpy as np

default_deck = np.array([card.get_index() for card in init_truco_deck()])

envido_actions = np.concatenate((envido_actions, response_actions))

truco_actions = np.concatenate((truco_actions, response_actions))



def encode_card_array(cards):
    if not isinstance(cards, list):
        cards = [cards]
    cards = [str(c) for c in cards]
    return  [1 if card in cards else 0 for card in default_deck]

    
def encode_envido(action):
    return [1 if a == action else 0 for a in envido_actions]

def encode_truco(action):
    return [1 if a == action else 0 for a in truco_actions]

In [5]:
encode_truco('truco')

[1, 0, 0, 0, 0]


In [6]:
c1 = ['C1', 'C2']
c2 = p0.hand

encode_card_array('C1')

NameError: name 'p0' is not defined

In [7]:
from player import Player
from dealer import Dealer
from game import TrucoGame

ModuleNotFoundError: No module named 'more_itertools'

In [8]:
num_players = 2

players = [Player(id) for id in range(num_players)]

dealer = Dealer()
dealer.deal_cards_in_order(players)

game = TrucoGame(players)

p0 = game.players[0]
p1 = game.players[1]

print(p0)
print(p1)

NameError: name 'TrucoGame' is not defined

In [223]:
game.take_action(p0, 'C4')

26-Sep-21 23:32:13 - INFO - Player 0 | Cards: ['E11'] played C4


In [224]:
game.take_action(p1, 'C5')

26-Sep-21 23:32:20 - INFO - Player 1 | Cards: ['B1'] played C5
26-Sep-21 23:32:20 - DEBUG - Player 1 | Cards: ['B1'] was rewarded 1 for winning hand.
26-Sep-21 23:32:20 - INFO - Hand finished.
26-Sep-21 23:32:20 - INFO - Player 0 | Cards: ['E11'] scored 0
26-Sep-21 23:32:20 - INFO - Player 1 | Cards: ['B1'] scored 1


In [64]:

state = []
for p, action in game.envido.envido_calls:
    state =[1 if player = p else 0, ]

SyntaxError: invalid syntax (<ipython-input-64-5a6e102a4a4f>, line 3)

In [227]:
def get_state(player, game):
    player_cards = encode_card_array(player.hand)
    
    mano = 1 if player == game.get_mano() else 0
    
    cards_played = []
    for p, c in game.card_game.cards_played:
        p_id = 1 if player == p else 0
        turn = [p_id, *encode_card_array(c)]
        cards_played.append(np.array(turn, dtype=np.int8))
    
    # Add padding for 6 turns
    for i in range(6 - len(cards_played)):
        cards_played.append(np.zeros(1 + 40, dtype=np.int8))
        
    envido_state = []
    for p, c in game.envido.envido_calls:
        p_id = 1 if player == p else 0
        turn = [p_id, *encode_envido(c)]
        envido_state.append(np.array(turn, dtype=np.int8))
    
    # Add padding 3 calls
    for i in range(3 - len(envido_state)):
        envido_state.append(np.zeros(1 + 4, dtype=np.int8))
        
    truco_state = []
    for p, c in game.truco.truco_calls:
        p_id = 1 if player == p else 0
        turn = [p_id, *encode_truco(c)]
        truco_state.append(np.array(turn, dtype = np.int8))
        
    # Add padding 5 calls
    for i in range(5 - len(truco_states)):
        envido_state.append(np.zeros(1 + 5, dtype=np.int8))
        
    return truco_state
    
    

In [226]:
get_state(p0, game)

[array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int8),
 array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int8),
 array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int8),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int8),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int8),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int8)]

In [ ]:
def myTriplet(x):
    return x + 1, x + 2, x + 3


myTriplet(1)